language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t atsyhanov/udemydocker -f Dockerfile.dev .

script:
  - docker run -e CI=true atsyhanov/udemydocker npm run test